[build]
builder = "nixpacks"
nixpacksPlan = """
{ pkgs, ... }:
{
  build.apt.pkgs = [];
  build.apt.archives = [];
  phases.build = ''
    ${pkgs.python310}/bin/python -m pip install --upgrade pip
    ${pkgs.python310}/bin/python -m pip install -r requirements.txt
  '';
  start.packageJson.scripts.start = "python a.py";
}
"""
